tasks:
  - init: |
      # 1. Install Solana CLI (new method)
        
      # 2. Add to PATH
      export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
      # 3. Install Anchor
      cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
      # 4. Install Yarn
      npm install -g yarn