[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
betting_program = "GLzWoeu6BZd4dMN5g7XetngX3Z6cPbr72d4xBY93EhLC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
