[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
betting_program = "Bpeo86v5xF7jBoSD5MheMDeppmfEQKRSRgYoCXmoWvRp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
