[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
betting_program = "8hLP8PTe7JqorACvs8oPeu7Uop8y6j2Fn9RQVp8ZBzxH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
